### ISSUE TITLE
Possible bugs in MSISEInputs

### ISSUE THREAD

**Issue by mgrutten** [ut-astria/orbdetpy#1]
I think there's a couple of bugs in the `MSISEInputs` java class.
- Lines 86 and 96 should contain integer division by 3, not modulo 3 (i.e. just `Integer.parseInt(p.substring(11, 13)) / 3`)
- Line 95 adds to `apvals[i]` without initialising it.  It should be set to zero before the loop starting at line 90.

**Comment by Shiva-Iyer** [comment]
Mark, thank you for this catch! I doubt I'd have caught it any time soon. Please let me know if you come across other issues.
