### ISSUE TITLE
maia.usno.navy.mil gone?

### ISSUE THREAD

**Issue by jsmorph** [ut-astria/orbdetpy#16]
When running

```Shell
python -c "from orbdetpy.astro_data import update_data; update_data();"
```

I get

```
HTTPConnectionPool(host='maia.usno.navy.mil', port=80): Max retries exceeded with url: /ser7/tai-utc.dat (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe02c06e6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by OrbitalMechanic** [comment]
I'm having the same problem with maia.usno.navy.mil. On the Naval Oceanographpy page at [https://www.usno.navy.mil/](url), there is a message that several links with one of them being maia.usno.navy.mil are undergoing modernization. Pinging maia.usno.navy.mil results in the message:

"ping: cannot resolve maia.usno.navy.mil: Unknown host"

It looks like that site no longer exists. Does anyone know that the new URL is?

Sam Dupree.

**Comment by OrbitalMechanic** [comment]
At [https://oceandata.sci.gsfc.nasa.gov/Ancillary/LUTs/common](url) there is a file named tai-utc.dat. The file contains a leap second table which appears to be up to date. Can someone confirm that the format of the data in the file is what orbdetpy requires?

Hope this helps.

Sam Dupree.

**Comment by Shiva-Iyer** [comment]
Release 2.0.4 fixes this by using a different server for the tai-utc.dat file. Will switch back to the usno site if and when it becomes operational.
