### ISSUE TITLE
definition of output vector from testsim example

### ISSUE THREAD

**Issue by Triettran75** [ut-astria/orbdetpy#9]
Please define the reference frame for the output for simulated measurements.  Here is the excerpt from the json file:
    "TrueState": {
      "Cartesian": [
        3.57960207669903E7,
        -2.2267515537321E7,
        -87938.3477596335,
        1625.07170292693,
        2610.77460296534,
        -2.09170251623871,
        -0.1904435227596349,
        0.1184685898367488,
        4.678533639820142E-4
      ]
    },
    "Time": "2018-01-01T00:02:54.000Z",
    "Station": "Station1",
    "RightAscension": -0.6282273730787877,
    "Declination": -0.09126966588071994
  },

**Comment by Shiva-Iyer** [comment]
As mentioned in docs/file_formats.md, if the Propagation.InertialFrame setting is not specified in your configuration, orbdetpy will default to EME2000 (aka J2000) and all state vector outputs will be in this frame. You can set this parameter to "GCRF" if you wish to use the latest definition of the Earth-centered International Celestial Reference Frame instead. No other frame may be used for this parameter.
